"""Gera os três relatórios acadêmicos. Requer reportlab, apenas para documentação."""
from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from xml.sax.saxutils import escape

OUT=Path('output/pdf')
OUT.mkdir(parents=True,exist_ok=True)
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='TitleCardio',fontName='Helvetica-Bold',fontSize=25,leading=29,textColor=colors.HexColor('#153D34'),spaceAfter=14))
styles.add(ParagraphStyle(name='SectionCardio',fontName='Helvetica-Bold',fontSize=12,leading=16,textColor=colors.HexColor('#153D34'),spaceBefore=13,spaceAfter=7))
styles.add(ParagraphStyle(name='BodyCardio',fontName='Helvetica',fontSize=10.5,leading=15,spaceAfter=9,alignment=TA_LEFT))

REPORTS={
'fluxo-conversacional':('Assistente conversacional',[
('Objetivo e base didática','O CardioIA simula a coleta inicial de informações fictícias em saúde. A Parte 1 usa IBM Watson Assistant com intenções, entidades, nós de diálogo e contexto; a Parte 2 usa Flask e HTML. A referência é PCV, capítulo 10, pp. 17-37 e 46-49. Docker foi acrescentado como requisito do projeto.'),
('Caminho da mensagem','Navegador > Flask > sessão da API v2 do Watson > reconhecimento de intenção e entidades > nó de diálogo > resposta e contexto > resumo na interface. O backend conserva o identificador remoto em SQLite e usa um token opaco na sessão do navegador. Cada perfil possui contexto separado; abas do mesmo perfil compartilham a sessão.'),
('Fluxos implementados','O catálogo contém 14 intenções e 70 exemplos de treinamento: saudação, ajuda, sintomas, medição, histórico, termos educativos, limites de conduta, urgência declarada, resumo, confirmação, correção, reinício, encerramento e extração. Cinco entidades reconhecem sintomas, tipo de medição, campo de correção, pressão com mmHg e frequência com bpm. As entidades de sintomas não são tratadas automaticamente como sintomas presentes.'),
('Exemplo de interação','Usuário: Quero registrar minha pressão. Watson: Informe a pressão completa em mmHg, por exemplo 120/80 mmHg. Usuário: 120/80 mmHg. Watson registra o valor literal e pede conferência. Ao solicitar o resumo, a interface exibe os valores informados. Uma confirmação explícita atualiza o indicador; uma correção retoma a coleta. Relatos livres recebem uma pergunta sobre início/duração.'),
('Contexto e exceções','As variáveis guardam etapa, relato, duração, histórico, medições e confirmação. Comandos globais precedem a captura de texto livre. Formatos incompletos recebem orientação; mensagens desconhecidas têm fallback e opções após repetição. Reiniciar cria nova sessão e remove o estado anterior. Expiração remota retorna erro controlado e permite iniciar outra conversa. O encerramento do diálogo termina o fluxo, e o botão Nova conversa cria um contexto limpo.'),
('PAGE',''),
('Integração e apresentação','O Flask serve a página e as rotas de conversa, extração e monitoramento. Valida tipo, tamanho e conteúdo das requisições; usa proteção CSRF e renderização por textContent. O resumo mostra somente campos permitidos. Ausências permanecem vazias; uma negação em um relato não vira diagnóstico. Segredos vêm do ambiente, nunca de JavaScript ou do JSON da skill.'),
('Execução reproduzível','docker compose --profile automacao up --build -d inicia aplicação, MongoDB e robô. A aplicação fica em localhost:5000. A imagem usa Python 3.12 e Gunicorn sem debug, executados como usuário sem privilégios. Os volumes conservam contexto, contagem de chamadas, medições e registros. O endpoint /health verifica o processo HTTP e não testa credenciais externas.'),
('Validação e estado da entrega','Foram aprovados 26 testes de backend/extração e cinco do robô em containers. O fluxo HTTP com APIs reais validou medições, confirmação, correção, isolamento entre clientes, Gemini integrado ao Watson e reinício. O Watson classificou 38 de 42 frases inéditas conforme a referência (90,5%); as quatro diferenças estão documentadas. A skill oficial foi exportada pela API v2 com 14 intenções, cinco entidades e 34 nós. O SDK usa assistant_id, environment_id e user_id opaco. Evidências e limitações constam em docs/VALIDACAO.md. A publicação no GitHub ficará a cargo do usuário.'),
('Limites','Trata-se de protótipo educacional com dados sintéticos. Não fornece diagnóstico, prescrição ou avaliação de emergência. A extração Gemini e a análise estatística são extensões separadas; a responsabilidade pela condução da conversa permanece no Watson. A interface solicita revisão dos dados antes de confirmação.'),
('Referências e arquivos','PCV: 2TIAOA - Fase 5 - Cap10 - Arquitetura Cognitiva dos LLMs Modernos, pp. 17-37, 46-49 e 60-63. Implementação: app.py, services/watson_service.py, services/clinical_summary.py, watson/build_skill.py e templates/index.html. Instruções completas e variáveis: README.md e .env.example.')]),
'ir-alem-1-extracao':('Ir Além 1 | Extração com Gemini',[
('Proposta e referência','A extensão organiza textos clínicos fictícios em JSON, usando prompting e API de modelo comercial, conforme PCV, capítulo 10, pp. 57-63. Foi escolhido texto, alternativa aceita pelo enunciado; não há análise de imagens nesta implementação. O provedor solicitado é Google AI Studio e o identificador configurado é gemini-3.5-flash-lite.'),
('Fluxo completo','Texto fictício > validação HTTP > busca no cache > reserva de tentativa no orçamento > API Gemini com instruções e esquema > validação Pydantic e evidência literal > apresentação de fatos e JSON > revisão humana > inclusão opcional do relato no contexto Watson. Sem conversa ativa, a extração continua disponível, mas não há inclusão automática no chat.'),
('Contrato estruturado','Cada fato possui campo, valor, evidencia e estado. Os campos permitidos são sintoma, pressao_arterial, frequencia_cardiaca, inicio, historico e adesao. Estado aceita afirmado, negado ou incerto. O esquema rejeita campos adicionais, valores vazios e mais de 30 fatos. Valor deve estar dentro da evidência, e a evidência deve estar no texto de origem. A resposta inclui modelo, texto original e indicação de revisão necessária.'),
('Prompt e proteção da fidelidade','extensions/generative/prompt.txt instrui a extrair somente declarações explícitas, conservar negações e incerteza, não resolver conflitos por suposição e ignorar instruções contidas no próprio relato. O backend também faz uma triagem conservadora de negações. Essas medidas não detectam todos os erros semânticos: o modelo ainda pode omitir fatos ou selecionar evidências incompletas.'),
('Exemplo executado na API real','Entrada: Minha frequência foi 72 bpm. Não tenho dor. Uma resposta esperada contém frequência 72 bpm afirmada e dor negada, cada uma com trecho literal correspondente. A aplicação executou o exemplo com sucesso na API real. As respostas estão registradas em docs/evidence/gemini-evaluation.json; o exemplo foi reavaliado a partir do cache dessa chamada.'),
('PAGE',''),
('Cota, cache e erros','O orçamento local limita app e robô a até 500 tentativas nas últimas 24 horas, com intervalo mínimo padrão de 10 segundos. A reserva usa transação SQLite para concorrência e persiste após recriação dos containers. O cache usa hash do modelo, prompt e texto, com validade de 24 horas. Não há retries automáticos: falhas consomem uma tentativa. A cota do Google pode ser diferente e inclui o uso de outras aplicações.'),
('Integração e execução','A biblioteca google-genai faz a chamada com response_mime_type application/json e esquema Pydantic. A interface exibe valores, estado, evidências e JSON bruto estruturado. O comando python -m extensions.generative.extract_clinical --text seguido do relato executa a mesma lógica no container. A confirmação inclui o texto original no Watson para conferência; não converte automaticamente uma inferência do modelo em medição clínica.'),
('Validação e avaliação real','Os testes locais cobrem formato, evidência inventada, negação, chave ausente, cache, persistência e concorrência do orçamento. São verificações do código com respostas controladas. A avaliação real incluiu seis casos: negação, ausência de medição, duas medidas, texto sem fatos, instrução embutida e incerteza. As seis saídas passaram esquema/evidências e os seis fatos da referência foram encontrados. Houve um fato adicional de início sustentado pelo texto, omitido pela referência e revisado como válido. Não se generalizam esses resultados para outros relatos; variação entre gerações não foi medida.'),
('Reprodução e evidências','Defina GEMINI_API_KEY no .env e recrie os containers. Use a aba Organizar relato ou o comando documentado no README. Consulte /api/status para tentativas locais. Nunca registre chaves junto das evidências. docs/VALIDACAO.md separa resultados reais de exemplos esperados e deve acompanhar este relatório.'),
('Referências','PCV, capítulo 10, pp. 57-60: APIs de modelos comerciais; pp. 60-63: integração híbrida. Documentação do modelo: ai.google.dev/gemini-api/docs/models/gemini-3.5-flash-lite. SDK: googleapis.github.io/python-genai/. Código: services/gemini_service.py, services/storage.py e extensions/generative/.')]),
'ir-alem-2-automacao':('Ir Além 2 | Automação e dados',[
('Base acadêmica e arquitetura','AIRPA, capítulo 2, apresenta SQLite (pp. 9-11), Isolation Forest (pp. 23-30) e MongoDB com Docker/pymongo (pp. 46-48). A solução usa essas tecnologias com Python periódico. SQLite é embutido no container do robô; MongoDB é um serviço do Compose com rede interna e volume próprio. A interpretação textual reutiliza Gemini, conforme o capítulo PCV.'),
('Preparação dos dados','A carga determinística usa random_state/semente 42 e um paciente fictício SIM-001. São 240 medições de treino e 63 de monitoramento, separadas por campo dataset. Os atributos são pressão sistólica, diastólica, frequência cardíaca e adesão. Existem três casos controlados: 301 com desvio injetado, 302 de referência e 303 com dado ausente. As distribuições escolhidas são artificiais, não faixas clínicas.'),
('Ciclo do robô','O robô cria um identificador de execução, registra o início, prepara a carga idempotente e treina o modelo com o subconjunto de treino. Busca medições ainda não avaliadas para a versão do modelo, valida os atributos, calcula predição/escore e persiste avaliações e alertas. Replica os eventos ao MongoDB, interpreta mensagens pendentes quando há chave/cota e registra o término. O intervalo padrão de 60 segundos é configurável.'),
('Técnica de IA','IsolationForest usa 100 árvores, contamination=0.08 e random_state=42. O parâmetro 0.08 calibra o corte no treino; não representa prevalência clínica nem garante 8% no monitoramento. Predição -1 gera anomalia_estatistica; demais casos recebem sem_desvio_detectado. Valores inválidos recebem dado_invalido e não entram no modelo. A versão é o hash de parâmetros, atributos, conjunto de treino e versão da implementação.'),
('PAGE',''),
('Persistência e rastreabilidade','SQLite mantém patients, measurements, evaluations, alerts, runs e outbox. Avaliações usam chave composta de medição e modelo; alertas usam identificador estável. MongoDB mantém runs, events e messages. Cada evento se vincula à medição/mensagem e execução de origem, com versão/modelo e data. A interpretação de mensagem conserva texto original e fatos com evidências.'),
('Recuperação de falhas','Resultados e eventos são gravados em uma transação local. A outbox é enviada ao MongoDB por upsert e marcada entregue somente após sucesso. Uma falha depois do envio pode causar reenvio, mas o mesmo identificador evita duplicação. Não há transação distribuída: os bancos convergem por reconciliação. A falha de conexão conserva eventos pendentes e status observável. Um bloqueio de arquivo no volume impede sobreposição de robôs.'),
('Resultados observados','Em execução real com SQLite e MongoDB nos containers, o primeiro ciclo processou 63 medições, gerou 11 alertas estatísticos e deixou zero eventos pendentes de sincronização. Cinco testes do robô aprovaram os casos controlados, idempotência e recuperação da fila após falha simulada. As três mensagens do MongoDB foram interpretadas pelo Gemini em chamadas reais, com evidências e vínculo às execuções. A recriação dos containers conservou os dados e os ciclos seguintes não duplicaram os alertas.'),
('Operação e limites','docker compose --profile automacao up --build -d inicia o fluxo. A aba Monitoramento mostra quantidades e ciclos; docker compose logs robot mostra identificadores e status. O comando --once permite execução isolada após parar o robô periódico. O conjunto inicial é estático: próximos ciclos não criam medições automaticamente; novas leituras podem ser inseridas por automation/add_measurement.py. Os dados persistem nos volumes durante encerramento normal.'),
('Referências e entregáveis','AIRPA: 2TIAOA - Fase 5 - Cap02 - Do Banco de Dados à Automação Inteligente, pp. 9-11, 23-30 e 46-48. Código: automation/robot.py, automation/data.py e automation/analysis.py. Esquema SQL: database/relational/schema.sql. Estruturas documentais: database/nonrelational/README.md. Execução, testes e limitações: README.md e docs/VALIDACAO.md.')])}

def footer(canvas,doc):
    canvas.setStrokeColor(colors.HexColor('#C8D8CE'))
    canvas.line(44,39,A4[0]-44,39)
    canvas.setFont('Helvetica',8)
    canvas.setFillColor(colors.HexColor('#53635D'))
    canvas.drawString(44,26,'CARDIOIA  /  FIAP FASE 5  /  DADOS FICTÍCIOS')
    canvas.drawRightString(A4[0]-44,26,str(doc.page))

for filename,(title,sections) in REPORTS.items():
    flow=[Paragraph('CARDIOIA / RELATÓRIO ACADÊMICO',styles['SectionCardio']),Paragraph(title,styles['TitleCardio'])]
    for heading,body in sections:
        if heading=='PAGE':
            flow.append(PageBreak())
        else:
            flow.extend([Paragraph(escape(heading),styles['SectionCardio']),Paragraph(escape(body),styles['BodyCardio'])])
    SimpleDocTemplate(str(OUT/f'{filename}.pdf'),pagesize=A4,rightMargin=44,leftMargin=44,topMargin=38,bottomMargin=53,
        title=title,author='Projeto CardioIA').build(flow,onFirstPage=footer,onLaterPages=footer)
    print(filename)
